package org.utn.tpfinalprogramacion3.security.enums;

public enum Permits {

    VER_LIBROS,
    VER_AUTORES,
    VER_RESENIAS,
    HACER_RESENIAS,
    ELIMINAR_RESENIA_PROPIA,
    VER_CARRITO,
    VER_TODOS_LOS_CARRITOS,//admin
    AGREGAR_LIBRO_AL_CARRITO,
    VER_SU_FACTURA,
    VER_LINK_MERCADOPAGO,
    VER_BIBLIOTECA,
    AGREGAR_LIBRO_FAVORITOS,
    VER_LIBRO_FAVORITO,
    ELIMINAR_LIBRO_FAVORITO,
    ELIMINAR_RESENIA,//ADMIN
    ELIMINAR_LIBRO,//ADMIN
    ELIMINAR_AUTOR,//ADMIN
    VER_GENEROS,
    ELIMINAR_GENEROS,//ADMIN
    ELIMINAR_USUARIOS,//ADMIN
    AGREGAR_GENEROS,//ADMIN
    AGREGAR_AUTOR,//ADMIN
    AGREGAR_LIBRO,//ADMIN
    MODIFICAR_LIBRO,//ADMIN
    MODIFICAR_AUTOR//ADMIN

}
